# Generated by Django 3.2.6 on 2021-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
