# Generated by Django 3.2.6 on 2021-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
